name: Terraform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-build:
    name: Terraform CI
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # ✅ NEW: Terraform Linting (tflint)
      - name: Lint Terraform Code
        uses: terraform-linters/tflint-action@c20ea3c31cb5508f08f6591a12fef7b6a62047e2

      # ✅ NEW: Terraform Security Scan (checkov)
      - name: Check Terraform Security
        uses: bridgecrewio/checkov-action@master

      - name: Terraform Plan
        run: terraform plan
